Exception in thread "main" com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in thread "main" com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in thread "main" com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in thread "main" com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in server:
com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in server:
com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in server:
com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:10)
Exception in server:
com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Exception in server:
com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Exception in server:
com.zeroc.Ice.InitializationException
    reason = "object adapter `Adapter' requires configuration"
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:929)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Exception in server:
com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:406)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:36)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:676)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:493)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1027)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at com.zeroc.IceInternal.Network.doBind(Network.java:400)
	... 7 more
Exception in server:
com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:406)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:36)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:676)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:493)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1027)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at com.zeroc.IceInternal.Network.doBind(Network.java:400)
	... 7 more
Exception in server:
com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:406)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:36)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:676)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:493)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1027)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at com.zeroc.IceInternal.Network.doBind(Network.java:400)
	... 7 more
Exception in server:
com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:406)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:36)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:676)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:493)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1027)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at com.zeroc.IceInternal.Network.doBind(Network.java:400)
	... 7 more
Exception in server:
com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:406)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:36)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:676)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:493)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1027)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:180)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:111)
	at org.example.Main.main(Main.java:11)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:565)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:344)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:301)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
	at com.zeroc.IceInternal.Network.doBind(Network.java:400)
	... 7 more
